title: Manuel Banza
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manuelbanza.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Manuel Banza # add your name
author-img: manuel_foto.jpg # add your photo
about-author: I am a data enthusiast who likes to work on data science projects related to mobility, cities and political issues. # add description
social-twitter: ManuelBanza # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: ManuelBanza # add your Github handle
social-linkedin: manuel-banza # add your Linkedin handle
social-email: manuelbanza@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
